export const communesKinshasa = [
  "Barumbu",
  "Bumbu",
  "Bandalungwa",
  "Gombe",
  "Kalamu",
  "Kasa-Vubu",
  "Kimbanseke",
  "Kinshasa",
  "Kintambo",
  "Kisenso",
  "Lemba",
  "Limete",
  "Lingwala",
  "Makala",
  "Maluku",
  "Masina",
  "Matete",
  "Mont-Ngafula",
  "Ngaba",
  "Ngaliema",
  "Nsele",
  "Selembao",
  "Ndjili",
  "Ngiri-Ngiri",
].sort((a, b) => {
  if (a > b) return 1;
  if (b === a) return 0;
  return -1;
});

export const quartiersParCommune = {
  Kintambo: [
    "Itimbiri",
    "Lisala",
    "Kilimani",
    "Lubudi-Luka",
    "Lubudi-Nganda",
    "Tshinkela",
    "Wenze",
    "Salongo",
  ],
  Ngaliema: [
    "Lubudi",
    "Mfinda",
    "Monganya",
    "Manenga",
    "Maman-Yemo",
    "Lonzo",
    "Museyi",
    "Kinkenda",
    "Kinsuka Pêcheur",
    "Joli Parc",
    "Basoko",
    "Congo",
    "Anciens Combattants",
    "Lukunga",
    "Kimpe",
    "Bangu",
    "Bumba",
    "Djelo Binza",
    "Binza Pigeon",
    "Punda",
    "Ngomba Kikusa",
  ],
  Gombe: [
    "Batetela",
    "Croix-Rouge",
    "Golf",
    "Gare",
    "Revolution",
    "Clinique",
    "Commerce",
    "Fleuve",
    "Lemera",
    "Haut Commandement",
  ],
  "Kasa-Vubu": [
    "Anciens Combattants",
    "Lubumbashi",
    "Salongo",
    "Katanga",
    "Assossa",
    "Lodja",
    "ONL",
  ],
  Kalamu: ["Matonge", "Kauka", "Pinzi", "Yolo Nord", "Yolo Sud", "20 mai"],
  Bandalungwa: [
    "Molard",
    "Lubudi",
    "Makelele",
    "Lumumba",
    "Camp Kokolo",
    "Kasa-Vubu",
    "Adoula",
    "Lingwala",
  ],
  Lingwala: [
    "30 Juin",
    "CNECI",
    "Voix du Peuple",
    "Lokole",
    "Ngunda Lokombe",
    "Pakadjuma",
    "Singa Mopepe",
    "Wenze",
    "PLC",
    "Lufungula",
  ],
  Makala: [
    "Bagata",
    "Bolima",
    "Kisantu",
    "Bahumbu",
    "Kabila",
    "Kwango",
    "Mabulu",
    "Mawanga",
    "Malala",
    "Mfidi",
    "Salongo",
    "Tampa",
    "Selo",
    "Mikasi",
  ],
  Lemba: [
    "Commercial",
    "Echangeur",
    "Ecole",
    "Foire",
    "Gombele",
    "Kemi",
    "Kimpwanza",
    "Livulu",
    "Mandradelle",
    "Masano",
    "Mbanza Lemba",
    "Salongo",
  ],
  Ngaba: ["Mukulua", "Mateba", "Mpila", "Baobab", "Luyi", "Bula-Mbemba"],
  Bumbu: [
    "Bula-Mbemba",
    "Dpiya",
    "Ubangi",
    "Kasai",
    "Lukenie",
    "Matadi",
    "Mbandaka",
    "Ntomba",
    "Mfimi",
    "Lieutenant Mbaki",
    "Mai-Ndombe",
    "Kwango",
    "Lokoro",
    "Mongala",
  ],
  Matete: [
    "Mandina",
    "Mboloko",
    "Ngilima",
    "Anunga",
    "Kinda",
    "Viaza",
    "Batandu",
    "Pululu",
    "Kinzazi",
    "Mongo",
    "Batende",
    "Mutoto",
    "Bahumbu",
    "Lokele",
    "Singa",
    "Kinsimbu",
    "Bateke",
    "Malandi",
    "Mpudi",
    "Kinsatu",
    "Tomba",
    "Vitamine",
    "Baboma",
    "Debonhomme",
    "Banunu",
    "Kunda",
    "Ngufu",
  ],
  Kisenso: [
    "17 Mai",
    "Bikanga",
    "Kabila",
    "Kitomesa",
    "Libération",
    "Mission",
    "Ngomba",
    "Quartier de la Paix",
    "Révolution",
    "Regideso",
    "Nsola",
    "Mujinga",
    "Mbuku",
    "Kumbu",
    "Kisenso-Gare",
    "Dingi-Dingi",
    "Amba",
  ],
  Limete: [
    "Agricole",
    "Kingabwa",
    "Mateba",
    "Mbamu",
    "Mombele",
    "Ndanu",
    "Résidentiel",
    "Salongo",
    "Nzadi",
    "Mfumu-Mvula",
    "Mososo",
    "Mayulu",
    "Masiala",
    "Industriel",
  ],
  Selembao: [
    "Kalunga",
    "Konde",
    "Kingu",
    "Liberation",
    "Madiata",
    "Kombe",
    "Ndobe",
    "Molende",
    "Inga",
    "Mbala",
    "Muana Ntunu",
    "Nkulu",
    "Badiadingi",
    "Cité Verte",
    "Herady",
    "Ngafani",
    "Pululu Mbambu",
    "Lubudi",
  ],
  "Mont-Ngafula": [
    "Kindele",
    "Mama Mobutu",
    "Masanga Mbila",
    "Plateau",
    "Matadi Mayo",
    "Kimbondo",
    "CPA Mushie",
    "Kimbuta",
    "Kimbuala",
    "Lutendele",
    "Mbudi",
    "Matadi Kibala",
    "Mitendi",
    "Ndjili-Kilamba",
    "Benseke",
    "Kimwenza",
    "Kilembo",
    "Mona",
    "Mama Yemo",
  ],
  Nsele: [
    "Bibwa",
    "Mikonga (Cité de Mpasa)",
    "Mpassa Maba",
    "Talangai",
    "Mikondo (Brasserie)",
    "Kikonle",
    "Badara",
  ],
  Ndjili: [
    "Quartier I",
    "Quartier III",
    "Quartier V",
    "Quartier VII",
    "Quartier IX",
    "Quartier XI",
    "Quartier XIII",
    "Quartier XII",
    "Quartier X",
    "Quartier VIII",
    "Quartier VI",
    "Quartier IV",
    "Quartier II",
  ],
  Masina: [
    "Abattoir",
    "Congo",
    "Imbali",
    "Télévision",
    "Tshango",
    "Pelende",
    "Mfumu Nsuka",
    "Mapela",
    "Lokali",
    "Mafuta Kizola",
    "Kimbangu",
    "Boba",
    "Efoloko",
    "Kasai",
    "Kivu",
    "Lubamba",
    "Mandiangu",
    "Matadi",
    "Nzuzi wa Mbombo",
    "Sans Fil",
    "Tshuenge",
  ],
  Kimbanseke: [
    "17 Mai",
    "Bamboma",
    "Boma",
    "Esanga",
    "Kasa-Vubu",
    "Kingasani",
    "Kutu",
    "Malonda",
    "Maviokele",
    "Mfumu Nkento",
    "Mokali",
    "Ngamazida",
    "Ngandu",
    "Nsumabwa",
    "Sakombi",
    "Salongo",
    "Révolution",
    "Nsanga",
    "Ngampani",
    "Mulie",
    "Mikondo",
    "Mbuala",
    "Mangana",
    "Luebo",
    "Kisantu IR Ben",
    "Kikimi",
    "Kamba Mulumba",
    "Dissasi",
    "Biyela",
    "Bahumbi",
  ],
  Barumbu: [
    "Bitshaku-Tshaku",
    "Funa I",
    "Funa II",
    "Kasai",
    "Libulu",
    "Mozindo",
    "Ndolo",
    "Tshimanga",
  ],
  "Ngiri-Ngiri": [
    "Diangenda",
    "Saio",
    "Assossa",
    "Karthoum",
    "Elengesa",
    "Diomi",
    "Petit-Petit",
    "24 Novembre",
  ],
  Kinshasa: [
    "Aketi",
    "Djalo",
    "Mongala",
    "Pende",
    "Ngbaka",
    "Madimba",
    "Boyoma",
  ],
  Maluku: [
    "Bita",
    "Ch. Major Leka",
    "Dumi",
    "Dumi_363",
    "Feshi",
    "Impuru",
    "Iye",
    "Kimbambula",
    "Kimpoko",
    "Kingakati",
    "Kingawa",
    "Kinzono",
    "Libaya",
    "Maess",
    "Mampu",
    "Mbankana",
    "Menkao",
    "Menkao IV",
    "Mongata",
    "Mutiene",
    "Ndakopembe",
    "Nsuni II",
    "Pema",
  ],
};

export type QuartiersParCommuneMap = typeof quartiersParCommune;
export const quartiersParCommuneSorted: QuartiersParCommuneMap = (
  Object.keys(quartiersParCommune) as Array<keyof QuartiersParCommuneMap>
)
  .sort((a, b) => a.localeCompare(b)) // tri alphabétique
  .reduce((acc, key) => {
    acc[key] = quartiersParCommune[key];
    return acc;
  }, {} as QuartiersParCommuneMap);

// === TRANSFORMATION ===

export type CommuneQuartierSelection = {
  name: string;
  quartiers: string[];
};

export const communesQuartiers: CommuneQuartierSelection[] = Object.entries(
  quartiersParCommuneSorted
).map(([commune, quartiers]) => ({
  name: commune,
  quartiers,
}));
